Fail CI if there is no CHANGELOG entry

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -34,16 +34,45 @@ before_script:
   - docker pull $DOCKER_IMAGE_CACHE_FROM || true
   - docker build --cache-from $DOCKER_IMAGE_CACHE_FROM --tag $DOCKER_LOCAL_TAG .
 
+.default_rules: &default_rules
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+      when: always
+    - if: $CI_COMMIT_BRANCH
+      when: always
+    - if: $CI_COMMIT_TAG
+      when: always
+
 pre_commit:
   image: python:3.13
+  <<: *default_rules
   before_script:
     - pip install pre-commit
   script:
     - pre-commit run --all-files
 
+changelog_check:
+  image:
+    name: alpine/git
+    entrypoint: ["/bin/sh", "-c"]
+  stage: test
+  before_script: []
+  script:
+    - |
+      git fetch --quiet origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
+      if ! git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME...HEAD | grep -q '^CHANGELOG.md$'; then
+        echo "ERROR: Merge requests must include a corresponding entry in CHANGELOG.md."
+        exit 1
+      fi
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+      when: always
+    - when: never
+
 tests:
   parallel: 10
   stage: test
+  <<: *default_rules
   script:
     - docker run
       --add-host=postgres:$POSTGRES_IP
@@ -61,6 +90,7 @@ tests:
 merge_test_results:
   image: python:3.12.2-alpine
   stage: test
+  <<: *default_rules
   needs: ["tests"]
   dependencies: ["tests"]
   when: always
@@ -106,6 +136,7 @@ pages:
 
 pg_badger:
   image: python:3.13
+  <<: *default_rules
   services:
     - docker:25.0.2-dind
     - redis:latest
